@echo off
cd /d "%~dp0"
echo Cleaning git lock...
if exist ".git\index.lock" del /f ".git\index.lock"
echo Adding all changes...
git add -A
echo Committing...
git commit -m "fix: store reference image as base64 in DB (no storage bucket auth needed)"
echo Pushing to GitHub...
git push
echo.
echo Done! Vercel will auto-deploy in ~1 minute.
pause
