@echo off
cd /d "%~dp0"
echo Cleaning git lock...
if exist ".git\index.lock" del /f ".git\index.lock"
echo Adding all changes...
git add -A
echo Committing...
git commit -m "feat: announcement home-only, hide sub-cats+custom from grid, ref image upload in customize, GIF fix, mobile hero fix"
echo Pushing to GitHub...
git push
echo.
echo Done! Vercel will auto-deploy in ~1 minute.
pause
